/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitap69_80;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BaoHien
 */
public class Bai89 extends javax.swing.JFrame {

    /**
     * Creates new form Bai89
     */
    public Bai89() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtSoSP = new javax.swing.JTextField();
        txtTienLuong = new javax.swing.JTextField();
        cbbPhanXuong = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSoSP1 = new javax.swing.JTextField();
        btnTinhLuong = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập thông tin nhân viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mã nv:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Số sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Phân xưởng:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tiền lương:");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSoSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoSPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoSPKeyTyped(evt);
            }
        });

        txtTienLuong.setBackground(new java.awt.Color(0, 255, 255));
        txtTienLuong.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTienLuong.setForeground(new java.awt.Color(102, 255, 0));
        txtTienLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTienLuong.setEnabled(false);

        cbbPhanXuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbPhanXuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        cbbPhanXuong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbPhanXuongItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Số sản phẩm chuẩn:");

        txtSoSP1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoSP1.setText("300");
        txtSoSP1.setEnabled(false);
        txtSoSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoSP1ActionPerformed(evt);
            }
        });

        btnTinhLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnDong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        tbNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        tbNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Phân xưởng", "Số sản phẩm", "Vượt chuẩn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNhanVien.setGridColor(new java.awt.Color(51, 51, 51));
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbPhanXuong, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnTinhLuong)
                        .addGap(33, 33, 33)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnDong))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbPhanXuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtSoSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbNhanVien.getModel();
        if(tbNhanVien.getSelectedRow()==-1){
            if(tbNhanVien.getRowCount()==0)
            JOptionPane.showMessageDialog(this, "Bảng đang rỗng");
            else
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần xóa");
        }
        else {
            int yesNo= JOptionPane.showConfirmDialog(this,"Bạn có muốn cập nhật hay không?","Confirm message", JOptionPane.YES_NO_OPTION);
            if (yesNo==0){
                NhanVien nhanvien = new NhanVien();
                nhanvien.setMaNV(txtMaNV.getText());
                nhanvien.setPhanXuong(cbbPhanXuong.getSelectedItem().toString());
                nhanvien.setSoSP(Integer.parseInt(txtSoSP.getText()));              
                //Cập nhật lại thông tin lên jTable
                model.setValueAt(txtMaNV.getText(),tbNhanVien.getSelectedRow(),0);
                model.setValueAt(cbbPhanXuong.getSelectedItem().toString(),tbNhanVien.getSelectedRow(),1);
                model.setValueAt(txtSoSP.getText(), tbNhanVien.getSelectedRow(),2);
                if (nhanvien.VuotChuan())
                    model.setValueAt("x", tbNhanVien.getSelectedRow(),3);  
                else
                    model.setValueAt("", tbNhanVien.getSelectedRow(),3);
            }
    }//GEN-LAST:event_btnSuaActionPerformed
    }
    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        // TODO add your handling code here
        DefaultTableModel model = (DefaultTableModel) tbNhanVien.getModel();
        txtMaNV.setText(model.getValueAt(tbNhanVien.getSelectedRow(),0).toString());
        cbbPhanXuong.setSelectedItem(model.getValueAt(tbNhanVien.getSelectedRow(),1).toString());
        txtSoSP.setText(model.getValueAt(tbNhanVien.getSelectedRow(),2).toString());
        
    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbNhanVien.getModel();
        ArrayList<NhanVien> nv = new ArrayList<NhanVien>();
        NhanVien nhanvien = new NhanVien();
        //Nhập thông tin nhân viên
        if (txtMaNV.getText().trim().equals("") || txtSoSP.getText().trim().equals(""))
            JOptionPane.showMessageDialog(this, "Có dữ liệu chưa nhập");
        else{
                    nhanvien.setMaNV(txtMaNV.getText());
                    nhanvien.setPhanXuong(cbbPhanXuong.getSelectedItem().toString());        
                    if (!txtSoSP.getText().matches("\\d+")) //Kiểm tra có phải là số không
                        JOptionPane.showMessageDialog(this, "Số sản phẩm phải nhập số");
                    else{
                        nhanvien.setSoSP(Integer.parseInt(txtSoSP.getText()));
                        nv.add(nhanvien);      
                  //Nhập thông tin nhân viên vào bảng
                    Vector<String> bang = new Vector<>();
                    bang.add(nhanvien.getMaNV());
                    bang.add(nhanvien.getPhanXuong());
                    bang.add(Integer.toString(nhanvien.getSoSP()));
                    if (nhanvien.VuotChuan())
                        bang.add("x");
                    //Hiện thông tin lên jTable
                    model.addRow(bang);
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    //tbNhanVien.setModel(model);
                    Clear();
                                  
                    }
    }//GEN-LAST:event_btnThemActionPerformed
}
    
    private void txtSoSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoSP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoSP1ActionPerformed

    private void cbbPhanXuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbPhanXuongItemStateChanged
        // TODO add your handling code here:
        if (cbbPhanXuong.getSelectedItem()=="A")
            txtSoSP1.setText("300");
        else
            txtSoSP1.setText("500");
    }//GEN-LAST:event_cbbPhanXuongItemStateChanged

    private void txtSoSPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoSPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoSPKeyTyped

    private void txtSoSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoSPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoSPKeyPressed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbNhanVien.getModel();
        if(tbNhanVien.getSelectedRow()==-1){
            if(tbNhanVien.getRowCount()==0)
            JOptionPane.showMessageDialog(this, "Bảng đang rỗng");
            else
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần xóa");
        }
        else {
            int yesNo= JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa hay không?","Confirm message", JOptionPane.YES_NO_OPTION);
            if (yesNo==0){
                model.removeRow(tbNhanVien.getSelectedRow());
                Clear();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
        NhanVien nhanvien = new NhanVien();
        nhanvien.setMaNV(txtMaNV.getText());
        nhanvien.setPhanXuong(cbbPhanXuong.getSelectedItem().toString());
        nhanvien.setSoSP(Integer.parseInt(txtSoSP.getText()));
        txtTienLuong.setText(Long.toString(nhanvien.TinhLuong()));
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnDongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai89.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai89.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai89.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai89.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai89().setVisible(true);
            }
        });
    }
    
    private class NhanVien{
        private String manv;
        private String phanxuong;
        private int sosp;
        NhanVien() { }
        NhanVien(String manv1, String phanxuong1, int sosp1){
            manv = manv1;
            phanxuong = phanxuong1;
            sosp = sosp1;
        }
        private void setMaNV(String manv){
            this.manv = manv;
        }
        private String getMaNV (){
            return manv;
        }
        private void setPhanXuong(String phanxuong){
            this.phanxuong = phanxuong;
        }
        private String getPhanXuong(){
            return phanxuong;
        }
        private void setSoSP(int sosp){
            this.sosp = sosp;
        }
        private int getSoSP(){
            return sosp;
        }
        private int getChuan(){
            if (phanxuong == "A")
                return 300;
            else
                return 500;
        }
        private boolean VuotChuan(){
            if (sosp > getChuan())
                return true;
            return false;
        }
        private long TinhLuong(){
            long luong;
            int chuan = getChuan();
            if (VuotChuan())
               luong = (sosp - chuan)*30000 + chuan*20000 ;
            else
                luong = sosp * 20000;
            return luong;
        }
        public String toString(){
            return manv; 
        }
    }
    private void Clear(){
        txtMaNV.setText("");
        cbbPhanXuong.setSelectedItem("A");
        txtSoSP.setText("");     
        txtTienLuong.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbPhanXuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSoSP;
    private javax.swing.JTextField txtSoSP1;
    private javax.swing.JTextField txtTienLuong;
    // End of variables declaration//GEN-END:variables
}
