/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baithuchanh3;

import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author BaoHien
 */
public class BaiThucHanh3 extends javax.swing.JFrame {

    /**
     * Creates new form BaiThucHanh3
     */
    public BaiThucHanh3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListTrai = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPhai = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddL = new javax.swing.JButton();
        btnAddAllLeft = new javax.swing.JButton();
        btnAddAllRight = new javax.swing.JButton();
        btnAddR = new javax.swing.JButton();
        btnAddListTrai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ListView Bai3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListTrai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jListTrai.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bóng đá", "Bóng chày", "Bóng rổ", "Bóng chuyền", "Cầu lông", "Bơi lội", "Dancing", "Gymness", "Tennis" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListTrai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 159, 246));

        jListPhai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(jListPhai);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 120, 166, 246));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DS môn thể thao");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 85, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Môn yêu thích");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 85, -1, -1));

        btnAddL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddL.setText(">");
        btnAddL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddL, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 136, 68, 35));

        btnAddAllLeft.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddAllLeft.setText(">>");
        btnAddAllLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllLeftActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAllLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 191, 68, 35));

        btnAddAllRight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddAllRight.setText("<<");
        btnAddAllRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllRightActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAllRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 298, 68, 35));

        btnAddR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddR.setText("<");
        btnAddR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddR, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 245, 68, 35));

        btnAddListTrai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddListTrai.setText("+");
        btnAddListTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddListTraiActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddListTrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 379, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //model
    DefaultListModel mdl1 = new DefaultListModel();
    DefaultListModel mdl2 = new DefaultListModel();
    
    
    private void btnAddAllLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllLeftActionPerformed
        // TODO add your handling code here:    
       ListModel mTrai = jListTrai.getModel();
       List<String> listTrai = new ArrayList<>();
       for (int i =0; i<mTrai.getSize(); i++)
           listTrai.add(mTrai.getElementAt(i).toString());
       for (int i=0; i<mTrai.getSize(); i++)
            mdl2.addElement(listTrai.get(i));
       jListPhai.setModel(mdl2);
       mdl1.removeAllElements();
       jListTrai.setModel(mdl1);             

    }//GEN-LAST:event_btnAddAllLeftActionPerformed
    private void btnAddLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLActionPerformed
        // TODO add your handling code here:        
        ListModel mTrai = jListTrai.getModel();
        List<String> listTrai = new ArrayList<>();
        for (int i =0; i<mTrai.getSize(); i++)
            listTrai.add(mTrai.getElementAt(i).toString());
        listTrai.remove(jListTrai.getSelectedIndex());        
        mdl2.addElement(jListTrai.getSelectedValue());        
        jListPhai.setModel(mdl2);
        Object[] arrTrai = listTrai.toArray(new String[0]);
        jListTrai.setListData((String[]) arrTrai);
        
       
    }//GEN-LAST:event_btnAddLActionPerformed

    private void btnAddListTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddListTraiActionPerformed
        // TODO add your handling code here:
        String nhap = JOptionPane.showInputDialog(null,"Nhập môn học mới");
        ListModel mTrai = jListTrai.getModel();
        List<String> listTrai = new ArrayList<>();
        for (int i =0; i<mTrai.getSize(); i++)
            listTrai.add(mTrai.getElementAt(i).toString());
        listTrai.add(nhap);
        Object[] arrTrai = listTrai.toArray(new String[0]);
        jListTrai.setListData((String[]) arrTrai);   
               
    }//GEN-LAST:event_btnAddListTraiActionPerformed

    private void btnAddRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRActionPerformed
        // TODO add your handling code here:
        ListModel mPhai = jListPhai.getModel();
        List<String> listPhai = new ArrayList<>();
        ListModel mTrai = jListTrai.getModel();
        List<String> listTrai = new ArrayList<>();
        for (int i =0; i<mPhai.getSize(); i++)
            listPhai.add(mPhai.getElementAt(i).toString());
        for (int i =0; i<mTrai.getSize(); i++)
            listTrai.add(mTrai.getElementAt(i).toString());
        listPhai.remove(jListPhai.getSelectedIndex());        
       // mdl1.addElement(jListPhai.getSelectedValue());
        listTrai.add(jListPhai.getSelectedValue());
        mdl2.remove(jListPhai.getSelectedIndex());
        Object[] arrPhai = listPhai.toArray(new String[0]);
        Object[] arrTrai = listTrai.toArray(new String[0]);
        jListPhai.setListData((String[]) arrPhai);
        jListTrai.setListData((String[]) arrTrai);
    }//GEN-LAST:event_btnAddRActionPerformed

    private void btnAddAllRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllRightActionPerformed
        // TODO add your handling code here:
        ListModel mPhai = jListPhai.getModel();
       List<String> listPhai = new ArrayList<>();
       for (int i =0; i<mPhai.getSize(); i++)
           listPhai.add(mPhai.getElementAt(i).toString());
       for (int i=0; i<mPhai.getSize(); i++)
            mdl1.addElement(listPhai.get(i));
       jListTrai.setModel(mdl1);
       mdl2.removeAllElements();
       jListPhai.setModel(mdl2);
       
    }//GEN-LAST:event_btnAddAllRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiThucHanh3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAllLeft;
    private javax.swing.JButton btnAddAllRight;
    private javax.swing.JButton btnAddL;
    private javax.swing.JButton btnAddListTrai;
    private javax.swing.JButton btnAddR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListPhai;
    private javax.swing.JList<String> jListTrai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
